/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef CRATE_H
#define CRATE_H

/* function declarations */
void init_crate(void);
void initialize_table_outputTable(void);
Netsnmp_Node_Handler outputTable_handler;
void initialize_table_groupsTable(void);
Netsnmp_Node_Handler groupsTable_handler;
void initialize_table_moduleTable(void);
Netsnmp_Node_Handler moduleTable_handler;
void initialize_table_sensorTable(void);
Netsnmp_Node_Handler sensorTable_handler;
void initialize_table_snmpCommunityTable(void);
Netsnmp_Node_Handler snmpCommunityTable_handler;
void initialize_table_psAuxiliaryTable(void);
Netsnmp_Node_Handler psAuxiliaryTable_handler;
void initialize_table_fanSpeedTable(void);
Netsnmp_Node_Handler fanSpeedTable_handler;
void initialize_table_analogInputTable(void);
Netsnmp_Node_Handler analogInputTable_handler;

/* column number definitions for table outputTable */
       #define COLUMN_OUTPUTINDEX		1
       #define COLUMN_OUTPUTNAME		2
       #define COLUMN_OUTPUTGROUP		3
       #define COLUMN_OUTPUTSTATUS		4
       #define COLUMN_OUTPUTMEASUREMENTSENSEVOLTAGE		5
       #define COLUMN_OUTPUTMEASUREMENTTERMINALVOLTAGE		6
       #define COLUMN_OUTPUTMEASUREMENTCURRENT		7
       #define COLUMN_OUTPUTMEASUREMENTTEMPERATURE		8
       #define COLUMN_OUTPUTSWITCH		9
       #define COLUMN_OUTPUTVOLTAGE		10
       #define COLUMN_OUTPUTADJUSTVOLTAGE		11
       #define COLUMN_OUTPUTCURRENT		12
       #define COLUMN_OUTPUTVOLTAGERISERATE		13
       #define COLUMN_OUTPUTVOLTAGEFALLRATE		14
       #define COLUMN_OUTPUTSUPERVISIONBEHAVIOR		15
       #define COLUMN_OUTPUTSUPERVISIONMINSENSEVOLTAGE		16
       #define COLUMN_OUTPUTSUPERVISIONMAXSENSEVOLTAGE		17
       #define COLUMN_OUTPUTSUPERVISIONMAXTERMINALVOLTAGE		18
       #define COLUMN_OUTPUTSUPERVISIONMAXCURRENT		19
       #define COLUMN_OUTPUTSUPERVISIONMAXTEMPERATURE		20
       #define COLUMN_OUTPUTCONFIGMAXSENSEVOLTAGE		21
       #define COLUMN_OUTPUTCONFIGMAXTERMINALVOLTAGE		22
       #define COLUMN_OUTPUTCONFIGMAXCURRENT		23
       #define COLUMN_OUTPUTSUPERVISIONMAXPOWER		24
       #define COLUMN_OUTPUTCURRENTRISERATE		25
       #define COLUMN_OUTPUTCURRENTFALLRATE		26
       #define COLUMN_OUTPUTTRIPTIMEMAXCURRENT		27
       #define COLUMN_OUTPUTHARDWARELIMITVOLTAGE		28
       #define COLUMN_OUTPUTHARDWARELIMITCURRENT		29
       #define COLUMN_OUTPUTCONFIGGAINSENSEVOLTAGE		30
       #define COLUMN_OUTPUTCONFIGOFFSETSENSEVOLTAGE		31
       #define COLUMN_OUTPUTCONFIGGAINTERMINALVOLTAGE		32
       #define COLUMN_OUTPUTCONFIGOFFSETTERMINALVOLTAGE		33
       #define COLUMN_OUTPUTCONFIGGAINCURRENT		34
       #define COLUMN_OUTPUTCONFIGOFFSETCURRENT		35
       #define COLUMN_OUTPUTUSERCONFIG		37
       #define COLUMN_OUTPUTREGULATIONMODE		38
       #define COLUMN_OUTPUTCONFIGMAXTEMPERATURE		39

/* column number definitions for table groupsTable */
       #define COLUMN_GROUPSINDEX		1
       #define COLUMN_GROUPSSWITCH		9

/* column number definitions for table moduleTable */
       #define COLUMN_MODULEINDEX		1
       #define COLUMN_MODULEDESCRIPTION		2
       #define COLUMN_MODULEAUXILIARYMEASUREMENTVOLTAGE		3
       #define COLUMN_MODULEHARDWARELIMITVOLTAGE		4
       #define COLUMN_MODULEHARDWARELIMITCURRENT		5
       #define COLUMN_MODULERAMPSPEEDVOLTAGE		6
       #define COLUMN_MODULERAMPSPEEDCURRENT		7
       #define COLUMN_MODULESTATUS		8
       #define COLUMN_MODULEEVENTSTATUS		9
       #define COLUMN_MODULEEVENTCHANNELSTATUS		10
       #define COLUMN_MODULEDOCLEAR		11
       #define COLUMN_MODULEAUXILIARYMEASUREMENTTEMPERATURE		12

/* column number definitions for table sensorTable */
       #define COLUMN_SENSORINDEX		1
       #define COLUMN_SENSORTEMPERATURE		2
       #define COLUMN_SENSORWARNINGTHRESHOLD		3
       #define COLUMN_SENSORFAILURETHRESHOLD		4
       #define COLUMN_SENSORALARMTHRESHOLD		6
       #define COLUMN_SENSORNAME		7
       #define COLUMN_SENSORID		8
       #define COLUMN_SENSORSTATUS		9

/* column number definitions for table snmpCommunityTable */
       #define COLUMN_SNMPACCESSRIGHT		1
       #define COLUMN_SNMPCOMMUNITYNAME		2

/* column number definitions for table psAuxiliaryTable */
       #define COLUMN_PSAUXILIARYINDEX		1
       #define COLUMN_PSAUXILIARYMEASUREMENTVOLTAGE		3
       #define COLUMN_PSAUXILIARYMEASUREMENTCURRENT		4

/* column number definitions for table fanSpeedTable */
       #define COLUMN_FANNUMBER		1
       #define COLUMN_FANSPEED		2

/* column number definitions for table analogInputTable */
       #define COLUMN_ANALOGINPUTINDEX		1
       #define COLUMN_ANALOGMEASUREMENTVOLTAGE		2
       #define COLUMN_ANALOGMEASUREMENTCURRENT		3
#endif /* CRATE_H */
