#ifndef SECANT_SRC_UTILITY_SECANTCONFIG_H
#define SECANT_SRC_UTILITY_SECANTCONFIG_H

#define SECANT_VERSION "0.0.0"
#define SECANT_MAJOR_VERSION 0
#define SECANT_MINOR_VERSION 0
#define SECANT_PATCH_VERSION 0

#endif //SECANT_SRC_UTILITY_SECANTCONFIG_H
